### ISSUE TITLE
Model property lookup returning undefined

### ISSUE THREAD

**Issue by d13** [kylefarris/ampersand-multiselect-view#1]
On line 225:
https://github.com/kylefarris/ampersand-multiselect-view/blob/master/ampersand-multiselect-view.js#L225

`lookupValues` should be `v`

**Comment by kylefarris** [comment]
Just FYI, I've addressed both bugs and published a patch to NPM as v0.0.4.

Thanks again.

**Comment by d13** [comment]
thanks!!
